Repository ethanuppal/marlin, pull requests merged in 2025-03, with the labels that each got.

#89 chore(deps): Streamline dependencies and `cargo-deny`
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  deny.toml
  examples/spade-project/Cargo.toml
  examples/spade-project/tests/simple_test.rs
  examples/verilog-project/Cargo.toml
  examples/verilog-project/src/tutorial.rs
  examples/verilog-project/tests/dpi_tutorial.rs
  examples/verilog-project/tests/dynamic_model_tutorial.rs
  examples/verilog-project/tests/simple_test.rs
  examples/verilog-project/tests/visibility_works.rs
  examples/veryl_project/.gitignore
  examples/veryl_project/Cargo.toml
  examples/veryl_project/src/lib.rs
  examples/veryl_project/tests/simple_test.rs
  src/lib.rs
  verilator/Cargo.toml
  veryl_project/src/main.sv
  veryl_project/src/main.sv.map
Labels: Code: Verilator, Infra: CI

#91 docs(veryl): Write Veryl quickstart
  book/SUMMARY.md
  book/introduction.md
  book/name.md
  book/spade/quickstart.md
  book/verilog/dpi.md
  book/verilog/dynamic.md
  book/verilog/quickstart.md
  book/veryl/quickstart.md
Labels: Documentation

#94 chore(deps): Switch to crates.io version of veryl-parser
  Cargo.lock
  Cargo.toml
  book/spade/quickstart.md
  book/verilog/dpi.md
  book/verilog/dynamic.md
  book/verilog/quickstart.md
  book/veryl/quickstart.md
  deny.toml
  examples/veryl_project/Cargo.toml
  examples/veryl_project/src/lib.rs
  examples/veryl_project/tests/simple_test.rs
  src/lib.rs
Labels: Documentation

#95 chore: Setup `cargo-release`
  Cargo.toml
  README.md
  book/SUMMARY.md
  book/internal/name.md
  book/internal/release-process.md
  examples/spade-project/Cargo.toml
  examples/verilog-project/Cargo.toml
  examples/veryl_project/Cargo.toml
Labels: Documentation

#97 chore(docs): Small docs updates
  README.md
  book/README.md
Labels: Documentation

#96 fix(spade): Don't `swim build` by default
  book/spade/quickstart.md
  examples/spade-project/tests/simple_test.rs
  language-support/spade/src/lib.rs
Labels: Documentation

#99 chore: Post-release 0.3.1
  Cargo.lock
  book/internal/release-process.md
Labels: Documentation

#100 fix(verilator): Support multiple models from one runtime
  Cargo.lock
  Cargo.toml
  book/spade/quickstart.md
  book/verilog/dpi.md
  book/verilog/dynamic.md
  book/verilog/quickstart.md
  book/veryl/quickstart.md
  examples/spade-project/tests/simple_test.rs
  examples/verilog-project/src/tutorial.rs
  examples/verilog-project/tests/dpi_tutorial.rs
  examples/verilog-project/tests/dynamic_model_tutorial.rs
  examples/verilog-project/tests/simple_test.rs
  examples/verilog-project/tests/visibility_works.rs
  examples/veryl_project/tests/simple_test.rs
  language-support/spade/src/lib.rs
  language-support/veryl/src/lib.rs
  verilator/Cargo.toml
  verilator/src/lib.rs
Labels: Documentation, Code: Verilator

#102 docs: Fix typo in README
  README.md
Labels: Documentation

#103 fix(verilator): Only log compile messages when actually rebuilding
  verilator/src/build_library.rs
  verilator/src/lib.rs
Labels: Code: Verilator

#105 fix(verilator): Only log blocking message when actually blocking
  verilator/src/lib.rs
Labels: Code: Verilator

#110 feat(verilog): Support `bool` and distinguish signed/unsigned integers over DPI
  book/verilog/dpi.md
  examples/verilog-project/src/dpi.sv
  examples/verilog-project/src/lib.rs
  examples/verilog-project/src/more_dpi.sv
  examples/verilog-project/tests/dpi_tutorial.rs
  language-support/verilog-macro/src/lib.rs
  verilator/src/dpi.rs
Labels: Documentation, Code: Verilog Support, Code: Verilator

#114 chore: Move `release-please` metadata into .github
  .github/.release-please-manifest.json
  .github/labels.yaml
  .github/release-please-config.json
  .github/workflows/release.yaml
Labels: Infra: CI

#122 docs: Fix broken link
  book/verilog/vcd.md
Labels: Documentation

#125 fix(verilog): Parse `input var` ports
  examples/verilog-project/src/lib.rs
  examples/verilog-project/src/parse_var.sv
  language-support/verilog-macro-builder/src/lib.rs
Labels: Code: Verilog Support
